[workspace]
resolver = "2"

members = ["arceos-vmm"]

[profile.release]
lto = true

[workspace.dependencies]
axstd = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm_inject_interrupt", features = ["ipi", "smp"] }
axconfig = { git = "https://github.com/arceos-hypervisor/arceos.git", branch = "vmm_inject_interrupt" }

axvm = { git = "https://github.com/arceos-hypervisor/axvm.git", branch = "inject_interrupt" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git", branch = "inject_interrupt" }
axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git", branch = "api" }

[patch."https://github.com/arceos-hypervisor/axvcpu.git"]
axvcpu = { path = "../axvcpu" }

[patch."https://github.com/arceos-hypervisor/axvisor_api.git"]
axvisor_api = { path = "../axvisor_api" }

[patch."https://github.com/arceos-hypervisor/x86_vcpu.git"]
x86_vcpu = { path = "../x86_vcpu" }

[patch."https://github.com/arceos-hypervisor/x86_vlapic.git"]
x86_vlapic = { path = "../x86_vlapic" }

[patch."https://github.com/arceos-hypervisor/axvm.git"]
axvm = { path = "../axvm" }

[patch."https://github.com/arceos-hypervisor/axdevice.git"]
axdevice = { path = "../axdevice" }

[patch."https://github.com/arceos-hypervisor/axdevice_crates.git"]
axdevice_base = { path = "../axdevice_crates/axdevice_base" }

[patch."https://github.com/arceos-hypervisor/arceos.git"]
axstd = { path = "../arceos-new/ulib/axstd", features = ["ipi", "smp", "irq"] }
axconfig = { path = "../arceos-new/modules/axconfig" }