# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "arceos"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# Guest vm physical cpu sets.
phys_cpu_sets = [1]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x42_0000
#entry_point = 0x028_0000 
# The location of image: "memory" | "fs".
# Load from file system.
#image_location = "fs"
# The file path of the kernel image.
#kernel_path = "arceos-aarch64.bin"
# The load address of the kernel image.
kernel_load_addr = 0x42_0000  
#kernel_load_addr = 0x4020_0000  
## Load from memory
 image_location = "memory"
## The file path of the kernel image.
kernel_path = "/home/hypervisor/arceos_hypervisor/guestOs/arceos/examples/helloworld/helloworld_aarch64-rk3568-pc.bin"
#kernel_path = "/home/hypervisor/arceos_hypervisor/arceos/examples/helloworld/helloworld_aarch64-qemu-virt.bin"
#kernel_path = "/home/hypervisor/arceos_hypervisor/somehal/target/aarch64-unknown-none/release/deps/test-3f0920a73955f4ed.bin"
## The file path of the device tree blob (DTB).
dtb_path = "/home/tool/rk3568_test1.dtb"
dtb_load_addr = 0x50_0000
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x40_0000, 0x700_0000, 0x7, 0], 
    #[0x0000_0000, 0x100_0000, 0x7, 0], 
]
#
# Device specifications
#
[devices]
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [   
    [
        "uart8250 UART",
        0xfe66_0000,
        0xfe66_0000,
        0x10000,
        0x1,
    ],
        [
        "gicd",
        0xfd40_0000,
        0xfd40_0000,
        0x10000,
        0x1,
    ],
            [
        "gicr",
        0xfd46_0000,
        0xfd46_0000,
        0x100000,
        0x1,
    ],
]